-- Migration: Portal Account Linking
-- PHASE 3.7.1

-- 1. Create PortalStatus enum
CREATE TYPE "PortalStatus" AS ENUM ('NONE', 'INVITED', 'ACTIVE', 'DISABLED');

-- 2. Create InvitationStatus enum
CREATE TYPE "InvitationStatus" AS ENUM ('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED');

-- 3. Add portalStatus to User table
ALTER TABLE "users" ADD COLUMN "portalStatus" "PortalStatus" NOT NULL DEFAULT 'NONE';

-- 4. Create PortalInvitation table (IDs will be generated by application)
CREATE TABLE "portal_invitations" (
  "id" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "userId" TEXT,
  "customerId" TEXT NOT NULL,
  "tokenHash" TEXT NOT NULL,
  "expiresAt" TIMESTAMP(3) NOT NULL,
  "status" "InvitationStatus" NOT NULL DEFAULT 'PENDING',
  "invitedById" TEXT,
  "invitedByName" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT current_timestamp,
  "acceptedAt" TIMESTAMP(3),
  "revokedAt" TIMESTAMP(3),
  "revokedReason" TEXT,
  CONSTRAINT "portal_invitations_pkey" PRIMARY KEY ("id")
);

-- 5. Add foreign key for PortalInvitation.userId
ALTER TABLE "portal_invitations" ADD CONSTRAINT "portal_invitations_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- 6. Add foreign key for PortalInvitation.customerId
ALTER TABLE "portal_invitations" ADD CONSTRAINT "portal_invitations_customerId_fkey"
  FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- 7. Add unique constraint for tokenHash
ALTER TABLE "portal_invitations" ADD CONSTRAINT "portal_invitations_tokenHash_unique" UNIQUE ("tokenHash");

-- 8. Add indexes
CREATE INDEX "portal_invitations_email_idx" ON "portal_invitations"("email");
CREATE INDEX "portal_invitations_tokenHash_idx" ON "portal_invitations"("tokenHash");
CREATE INDEX "portal_invitations_customerId_idx" ON "portal_invitations"("customerId");
CREATE INDEX "portal_invitations_userId_idx" ON "portal_invitations"("userId");
CREATE INDEX "portal_invitations_status_idx" ON "portal_invitations"("status");
